version: '2'

services:
  redis:
    image: redis:5
    volumes:
      - ./redis_persistence:/data

  redis-cli:
    image: redis:5
    depends_on:
      - redis
    command: 'redis-cli -h redis'

  node-base:
    image: node:12
    user: 'node'
    working_dir: /home/node/app
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/home/node/app

  node-needs-redis:
    extends: node-base
    depends_on:
      - redis
